# Generated by Django 5.1.1 on 2024-12-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0004_application_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
