# Generated by Django 5.1.1 on 2024-12-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0005_item_display_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.AddField(
            model_name='application',
            name='password',
            field=models.CharField(default='password', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='username',
            field=models.CharField(default='username', max_length=255),
            preserve_default=False,
        ),
    ]
