# Generated by Django 5.1.1 on 2024-12-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0008_itemrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_max_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
