# Generated by Django 5.1.1 on 2024-12-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0010_profile_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='times_suspended',
            field=models.IntegerField(default=0),
        ),
    ]
