# Generated by Django 5.1.1 on 2024-12-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0011_profile_times_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='was_selected',
            field=models.BooleanField(default=False),
        ),
    ]
