# Generated by Django 5.1.3 on 2024-12-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0011_profile_times_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complaints_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='transactions_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
