# Generated by Django 5.1.3 on 2024-12-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0012_bid_was_selected'),
        ('bidder', '0012_profile_complaints_count_profile_transactions_count'),
    ]

    operations = [
    ]
