# Generated by Django 5.1.3 on 2024-12-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0013_merge_20241212_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='complaints_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='transactions_count',
        ),
    ]
