# Generated by Django 5.1.3 on 2024-12-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0014_remove_profile_complaints_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_rating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
