# Generated by Django 5.1.3 on 2024-12-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0015_item_has_rating_item_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
