# Generated by Django 5.1.1 on 2024-12-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0016_transaction_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='rating',
            new_name='buyer_rating',
        ),
        migrations.AddField(
            model_name='transaction',
            name='rated_by_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rated_by_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
